name: Daily build of GCC trunk

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-build:
    uses: ${GITHUB_REPOSITORY}/.github/workflows/daily-build-template.yml@${GITHUB_SHA}
    with: { image: clang, build_name: llvm, command: build.sh, build: llvm-trunk }
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
