name: All daily builds

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      restrict_to:
        description: 'Build only things matching this build name'
        required: true
        default: '.*'

jobs:
  daily-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # IMPORTANT: when you add a build here you must also add an entry in remove_old_compilers.sh
          # in the infra repository.
          # These are slowly replacing the ones in admin-daily-builds.sh
          - { image: clang, build_name: llvm, command: build.sh, build: llvm-trunk }
          - { image: gcc, build_name: gcc, command: build.sh, build: trunk }
          - { image: gcc, build_name: gcc_contracts, command: build.sh, build: lock3-contracts-trunk }
          - { image: gcc, build_name: gcc_contracts_labels, command: build.sh, build: lock3-contracts-labels-trunk }
          - { image: gcc, build_name: gcc_modules, command: build.sh, build: cxx-modules-trunk }
          - { image: gcc, build_name: gcc_coroutines, command: build.sh, build: cxx-coroutines-trunk }
          - { image: gcc, build_name: gcc_gccrs_master, command: build.sh, build: gccrs-master }
          - { image: clang, build_name: clang, command: build.sh, build: trunk }
          - { image: clang, build_name: clang_assertions, command: build.sh, build: assertions-trunk }
          - { image: clang, build_name: clang_cppx, command: build.sh, build: cppx-trunk }
          - { image: clang, build_name: clang_cppx_ext, command: build.sh, build: cppx-ext-trunk }
          - { image: clang, build_name: clang_cppx_p2320, command: build.sh, build: cppx-p2320-trunk }
          - { image: clang, build_name: clang_relocatable, command: build.sh, build: relocatable-trunk }
          - { image: clang, build_name: clang_autonsdmi, command: build.sh, build: autonsdmi-trunk }
          - { image: clang, build_name: clang_lifetime, command: build.sh, build: lifetime-trunk }
          - { image: clang, build_name: clang_llvmflang, command: build.sh, build: llvmflang-trunk }
          - { image: clang, build_name: clang_patmat, command: build.sh, build: patmat-trunk }
          - { image: clang, build_name: clang_parmexpr, command: build-parmexpr.sh, build: trunk }
          - { image: go, build_name: go, command: build.sh, build: trunk }
          - { image: misc, build_name: tinycc, command: build-tinycc.sh, build: trunk }
          - { image: misc, build_name: cc65, command: buildcc65.sh, build: trunk }
          - { image: misc, build_name: mrustc, command: build-mrustc.sh, build: master }
          - { image: misc, build_name: cproc, command: build-cproc.sh, build: master }
          - { image: misc, build_name: rustc-cg-gcc_master, command: build-rustc-cg-gcc.sh, build: master }
          - { image: misc, build_name: SPIRV-Tools, command: build-spirv-tools.sh, build: master }
            # see https://github.com/compiler-explorer/clang-builder/issues/28
            #- { image: clang, build_name: clang_embed, command: build.sh, build: embed-trunk }
            # see https://github.com/compiler-explorer/clang-builder/issues/29
            #- { image: clang, build_name: llvm_spirv, command: build.sh, build: llvm-spirv }

    name: Daily build of ${{ matrix.build_name }}
    runs-on: [ 'self-hosted', 'ce', 'ubuntu' ]

    steps:
      - name: Get previous build version number, and start the run
        id: previous
        run: |
          echo ::set-output name=revision::$(curl -sf https://compiler-explorer.s3.amazonaws.com/opt/.buildrevs/${{ matrix.build_name }} || true)
          ./pre-run.sh
      - name: Daily build of ${{ matrix.build_name }}
        id: build
        run: |
          if [[ -n "${{ github.event.inputs.restrict_to }}" ]] && [[ ! "${{ matrix.build_name }}" =~ ^${{ github.event.inputs.restrict_to }}$ ]]; then
            echo ::set-output name=status::SKIPPED
            exit 0
          fi

          mkdir dist
          echo ::group::Docker build
          docker run -v$(pwd)/dist:/dist --rm compilerexplorer/${{ matrix.image }}-builder \
            bash ${{ matrix.command }} ${{ matrix.build }} \
            /dist "${{ steps.previous.outputs.revision }}" | tee output.log
          echo ::endgroup::
          echo ::group::Translate docker output into GH variables
          gawk -e 'match($0, /^ce-build-(\w+):(.*)/, m) { print "::set-output name=" m[1] "::" m[2]; }' output.log
          echo ::endgroup::
      - name: Get output filename
        if: ${{ steps.build.outputs.status != 'SKIPPED' }}
        id: filenames
        run: |
          echo ::set-output name=source::$(pwd)/dist/$(basename ${{ steps.build.outputs.output }})
          echo ::set-output name=s3dest::s3://compiler-explorer/opt/$(basename ${{ steps.build.outputs.output }})
          echo ${{ steps.build.outputs.revision }} > ${{ matrix.build_name }}
      - name: Copy output to S3
        if: ${{ steps.build.outputs.status != 'SKIPPED' }}
        uses: prewk/s3-cp-action@v2
        with:
          source: ${{ steps.filenames.outputs.source }}
          dest: ${{ steps.filenames.outputs.s3dest }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Copy revision to S3
        if: ${{ steps.build.outputs.status != 'SKIPPED' }}
        uses: prewk/s3-cp-action@v2
        with:
          source: ${{ matrix.build_name }}
          dest: s3://compiler-explorer/opt/.buildrevs/${{ matrix.build_name }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Update build logs
        if: always()
        run: ./post-run.sh "${{ matrix.build_name }}" "${{ steps.build.outputs.status }}" "${{ steps.filenames.outputs.s3dest }}" "${{ steps.previous.outputs.start }}"
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
